trigger: 
 - main

pool:
   name: Self-Hosted-Agent

variables:
  - group: dev
stages:
- stage: Build
  jobs:
  - job:
    displayName: Build the application
    steps: 
    - task: Go@0
      displayName: "Go Get"
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: Go@0
      displayName: "Go Build"
      inputs:
        command: 'build'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: qetza.replacetokens.replacetokens-task.replacetokens@3
      displayName: 'Replace image version in deployment.yaml'
      inputs:
        rootDirectory: '$(System.DefaultWorkingDirectory)'
        targetFiles: 'deployment.yaml'
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'deployment.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
         artifactName: drop

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)'
        repository: $(AWS_ECR_MAGE_URI)

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS_Service'
        regionName: $(AWS_REGION)
        imageSource: 'imagename'
        sourceImageName: $(AWS_ECR_MAGE_URI)
        sourceImageTag: $(Build.BuildId)
        pushTag: $(Build.BuildId)
        repositoryName: $(AWS_ECR_REPOSITORY_NAME)
- stage: Dev
  dependsOn: Build
  jobs:
  - deployment:
    displayName: Dev deploy
    environment: dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: kubectl apply -f deployment.yaml
             displayName: 'Dev Deploy'