trigger:
- main


jobs:
- job: BuildAndTest
  workspace:
    clean: all
  pool:
    vmImage: Ubuntu-latest

  container: golang:1.16
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo inside container
      
        echo Hello world
        echo "$(cat /etc/os-release)"
  - task: Go@0
    displayName: "Go Get"
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    displayName: "Go Build"
    inputs:
      command: 'build'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    displayName: 'Go Test'
    inputs:
      command: 'test'
      arguments: './...'
  - task: CopyFiles@2
    displayName: "Copy files to ArtifactStaging"
    inputs:
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
       artifactName: drop
